### ISSUE TITLE
Could not find generator browser_id:install.

### ISSUE THREAD

**Issue by vladikoff** [skyschub/devise_browserid_authenticatable#11]
Could not find generator browser_id:install.

What do I need to do to get this generator?

**Comment by DeadSuperHero** [comment]
Seems to show up just fine in 1.3.0 of the gem, did not appear in 1.3.1 on my end. :/

**Comment by scivola** [comment]
The following commit is wrong:
https://github.com/denschub/devise_browserid_authenticatable/commit/263695cfe2108dfb968728c887a576f823e5470f#devise_browserid_authenticatable.gemspec

Change

``` ruby
 s.require_paths = %w('lib')
```

to

``` ruby
 s.require_paths = %w(lib)
```

**Comment by skyschub** [comment]
S**t. Sorry folks. I'm really sorry. I was on vacation and totally lost the ticket. I'll release the fix right now.
