### ISSUE TITLE
How to seed a user

### ISSUE THREAD

**Issue by alain-andre** [skyschub/devise_browserid_authenticatable#12]
Hi, I need to seed an admin user (my users have role), how can I create the `encrypted_password` ?
Thanks.

**Comment by skyschub** [comment]
Creating a user has nothing to do with my gem. You can just add a user with

``` ruby
User.create!({
  email: "guy@gmail.com",
  roles: ["admin"],
  password: "123",
  password_confirmation: "123"
})
```

for example. As usual.

**Comment by alain-andre** [comment]
Hoo, ok.
I feel stupid not to have tried a simple creation :p 
Thanks for reply.
